language: rust
rust:
  - stable
  - beta
  - nightly
os:
  - linux
  - windows
cache:
  cargo: true
matrix:
  allow_failures:
    - beta
    - nightly
script:
  - cargo clean
  - cargo build
  - cargo test