jobs:
- template: 'azure-template-unix.yml'
  parameters:
    name: 'macOS_stable'
    vmImage: 'xcode9-macos10.13'
    toolchain: 'stable'

- template: 'azure-template-unix.yml'
  parameters:
    name: 'macOS_beta'
    vmImage: 'xcode9-macos10.13'
    toolchain: 'beta'

- template: 'azure-template-unix.yml'
  parameters:
    name: 'macOS_nightly'
    vmImage: 'xcode9-macos10.13'
    toolchain: 'nightly'

- template: 'azure-template-unix.yml'
  parameters:
    name: 'macOS_1_33_0'
    vmImage: 'xcode9-macos10.13'
    toolchain: '1.33.0'

- template: 'azure-template-unix.yml'
  parameters:
    name: 'Linux_stable'
    vmImage: 'ubuntu-16.04'
    toolchain: 'stable'

- template: 'azure-template-windows.yml'
  parameters:
    name: 'Windows_default_features'
    vmImage: 'vs2017-win2016'
    toolchain: 'stable'
